2024-01-16 21:19:14,154 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-16 21:19:14,157 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Configure stats pid to 5264
2024-01-16 21:19:14,158 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Loading settings from /home/filipeckijan/.config/wandb/settings
2024-01-16 21:19:14,159 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/dziew/Documents/studia/ium/ium-projekt/models/DBSCAN/wandb/settings
2024-01-16 21:19:14,159 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-16 21:19:14,160 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-16 21:19:14,162 INFO    MainThread:5264 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/c/Users/dziew/Documents/studia/ium/ium-projekt/models/DBSCAN/wandb/run-20240116_211914-4ub1fado/logs/debug.log
2024-01-16 21:19:14,164 INFO    MainThread:5264 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/c/Users/dziew/Documents/studia/ium/ium-projekt/models/DBSCAN/wandb/run-20240116_211914-4ub1fado/logs/debug-internal.log
2024-01-16 21:19:14,165 INFO    MainThread:5264 [wandb_init.py:init():566] calling init triggers
2024-01-16 21:19:14,166 INFO    MainThread:5264 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-16 21:19:14,167 INFO    MainThread:5264 [wandb_init.py:init():591] re-initializing run, found existing run on stack: mgatar51
2024-01-16 21:19:14,170 INFO    MainThread:5264 [wandb_run.py:_finish():1962] finishing run ium-team/ium-projekt/mgatar51
2024-01-16 21:19:14,174 INFO    MainThread:5264 [jupyter.py:save_history():445] not saving jupyter history
2024-01-16 21:19:14,175 INFO    MainThread:5264 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-16 21:19:14,177 INFO    MainThread:5264 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-01-16 21:19:14,178 INFO    MainThread:5264 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-16 21:19:14,179 INFO    MainThread:5264 [wandb_run.py:_restore():2185] restore
2024-01-16 21:19:14,180 INFO    MainThread:5264 [wandb_run.py:_restore():2191] restore done
2024-01-16 21:19:19,720 INFO    MainThread:5264 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-01-16 21:19:19,721 INFO    MainThread:5264 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-01-16 21:19:19,728 INFO    MainThread:5264 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-01-16 21:19:19,776 INFO    MainThread:5264 [wandb_init.py:init():616] starting backend
2024-01-16 21:19:19,776 INFO    MainThread:5264 [wandb_init.py:init():620] setting up manager
2024-01-16 21:19:19,790 INFO    MainThread:5264 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-16 21:19:19,791 INFO    MainThread:5264 [wandb_init.py:init():628] backend started and connected
2024-01-16 21:19:19,819 INFO    MainThread:5264 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-16 21:19:19,820 INFO    MainThread:5264 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-16 21:19:19,820 INFO    MainThread:5264 [wandb_init.py:init():720] updated telemetry
2024-01-16 21:19:19,942 INFO    MainThread:5264 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-01-16 21:19:21,366 INFO    MainThread:5264 [wandb_run.py:_on_init():2254] communicating current version
2024-01-16 21:19:21,632 INFO    MainThread:5264 [wandb_run.py:_on_init():2263] got version response 
2024-01-16 21:19:21,633 INFO    MainThread:5264 [wandb_init.py:init():804] starting run threads in backend
2024-01-16 21:19:21,822 INFO    MainThread:5264 [wandb_run.py:_console_start():2233] atexit reg
2024-01-16 21:19:21,823 INFO    MainThread:5264 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-01-16 21:19:21,823 INFO    MainThread:5264 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-01-16 21:19:21,823 INFO    MainThread:5264 [wandb_run.py:_redirect():2178] Redirects installed.
2024-01-16 21:19:21,826 INFO    MainThread:5264 [wandb_init.py:init():847] run started, returning control to user process
2024-01-16 21:24:25,414 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-16 21:24:25,416 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Configure stats pid to 5264
2024-01-16 21:24:25,416 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Loading settings from /home/filipeckijan/.config/wandb/settings
2024-01-16 21:24:25,417 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/dziew/Documents/studia/ium/ium-projekt/models/DBSCAN/wandb/settings
2024-01-16 21:24:25,418 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-16 21:24:25,419 INFO    MainThread:5264 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-16 21:24:25,420 INFO    MainThread:5264 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/c/Users/dziew/Documents/studia/ium/ium-projekt/models/DBSCAN/wandb/run-20240116_212425-goz6fjpj/logs/debug.log
2024-01-16 21:24:25,422 INFO    MainThread:5264 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/c/Users/dziew/Documents/studia/ium/ium-projekt/models/DBSCAN/wandb/run-20240116_212425-goz6fjpj/logs/debug-internal.log
2024-01-16 21:24:25,423 INFO    MainThread:5264 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fecaeb00c10>
2024-01-16 21:24:25,424 INFO    MainThread:5264 [wandb_init.py:init():566] calling init triggers
2024-01-16 21:24:25,426 INFO    MainThread:5264 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-16 21:24:25,427 INFO    MainThread:5264 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 4ub1fado
2024-01-16 21:24:25,432 INFO    MainThread:5264 [wandb_run.py:_finish():1962] finishing run ium-team/ium-projekt/4ub1fado
2024-01-16 21:24:25,437 INFO    MainThread:5264 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-16 21:24:25,441 INFO    MainThread:5264 [wandb_run.py:_restore():2185] restore
2024-01-16 21:24:25,443 INFO    MainThread:5264 [wandb_run.py:_restore():2191] restore done
2024-01-16 21:24:31,845 INFO    MainThread:5264 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-01-16 21:24:31,847 INFO    MainThread:5264 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-01-16 21:24:31,864 INFO    MainThread:5264 [wandb_run.py:_footer_sync_info():3816] logging synced files
